# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_remotecontroldockwidget.ui'
#
# Created: Tue Mar  4 18:18:12 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RemoteControlDockWidget(object):
    def setupUi(self, RemoteControlDockWidget):
        RemoteControlDockWidget.setObjectName(_fromUtf8("RemoteControlDockWidget"))
        RemoteControlDockWidget.resize(410, 443)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.serverTab = QtGui.QWidget()
        self.serverTab.setObjectName(_fromUtf8("serverTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.serverTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.serverAddressLineEdit = QtGui.QLineEdit(self.serverTab)
        self.serverAddressLineEdit.setEnabled(False)
        self.serverAddressLineEdit.setObjectName(_fromUtf8("serverAddressLineEdit"))
        self.gridLayout.addWidget(self.serverAddressLineEdit, 0, 1, 1, 1)
        self.portLabel = QtGui.QLabel(self.serverTab)
        self.portLabel.setObjectName(_fromUtf8("portLabel"))
        self.gridLayout.addWidget(self.portLabel, 1, 0, 1, 1)
        self.serverAddressLabel = QtGui.QLabel(self.serverTab)
        self.serverAddressLabel.setObjectName(_fromUtf8("serverAddressLabel"))
        self.gridLayout.addWidget(self.serverAddressLabel, 0, 0, 1, 1)
        self.portSpinBox = QtGui.QSpinBox(self.serverTab)
        self.portSpinBox.setEnabled(False)
        self.portSpinBox.setMinimum(1)
        self.portSpinBox.setMaximum(65535)
        self.portSpinBox.setProperty("value", 9615)
        self.portSpinBox.setObjectName(_fromUtf8("portSpinBox"))
        self.gridLayout.addWidget(self.portSpinBox, 1, 1, 1, 1)
        self.portEditToolButton = QtGui.QToolButton(self.serverTab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/draw-freehand.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.portEditToolButton.setIcon(icon)
        self.portEditToolButton.setCheckable(True)
        self.portEditToolButton.setObjectName(_fromUtf8("portEditToolButton"))
        self.gridLayout.addWidget(self.portEditToolButton, 1, 2, 1, 1)
        self.serverAddressEditToolButton = QtGui.QToolButton(self.serverTab)
        self.serverAddressEditToolButton.setIcon(icon)
        self.serverAddressEditToolButton.setCheckable(True)
        self.serverAddressEditToolButton.setObjectName(_fromUtf8("serverAddressEditToolButton"))
        self.gridLayout.addWidget(self.serverAddressEditToolButton, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startServerToolButton = QtGui.QToolButton(self.serverTab)
        self.startServerToolButton.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/call-start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startServerToolButton.setIcon(icon1)
        self.startServerToolButton.setIconSize(QtCore.QSize(32, 32))
        self.startServerToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.startServerToolButton.setObjectName(_fromUtf8("startServerToolButton"))
        self.horizontalLayout.addWidget(self.startServerToolButton)
        self.stopServerToolButton = QtGui.QToolButton(self.serverTab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/call-stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopServerToolButton.setIcon(icon2)
        self.stopServerToolButton.setIconSize(QtCore.QSize(32, 32))
        self.stopServerToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.stopServerToolButton.setObjectName(_fromUtf8("stopServerToolButton"))
        self.horizontalLayout.addWidget(self.stopServerToolButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.serverTab, _fromUtf8(""))
        self.clientTab = QtGui.QWidget()
        self.clientTab.setObjectName(_fromUtf8("clientTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.clientTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.clientAddressLineEdit = QtGui.QLineEdit(self.clientTab)
        self.clientAddressLineEdit.setEnabled(False)
        self.clientAddressLineEdit.setObjectName(_fromUtf8("clientAddressLineEdit"))
        self.gridLayout_2.addWidget(self.clientAddressLineEdit, 0, 1, 1, 1)
        self.clientPortLabel = QtGui.QLabel(self.clientTab)
        self.clientPortLabel.setObjectName(_fromUtf8("clientPortLabel"))
        self.gridLayout_2.addWidget(self.clientPortLabel, 1, 0, 1, 1)
        self.clientAddressLabel = QtGui.QLabel(self.clientTab)
        self.clientAddressLabel.setObjectName(_fromUtf8("clientAddressLabel"))
        self.gridLayout_2.addWidget(self.clientAddressLabel, 0, 0, 1, 1)
        self.clientPortSpinBox = QtGui.QSpinBox(self.clientTab)
        self.clientPortSpinBox.setEnabled(False)
        self.clientPortSpinBox.setMinimum(1)
        self.clientPortSpinBox.setMaximum(65535)
        self.clientPortSpinBox.setProperty("value", 9615)
        self.clientPortSpinBox.setObjectName(_fromUtf8("clientPortSpinBox"))
        self.gridLayout_2.addWidget(self.clientPortSpinBox, 1, 1, 1, 1)
        self.clientPortEditToolButton = QtGui.QToolButton(self.clientTab)
        self.clientPortEditToolButton.setIcon(icon)
        self.clientPortEditToolButton.setCheckable(True)
        self.clientPortEditToolButton.setObjectName(_fromUtf8("clientPortEditToolButton"))
        self.gridLayout_2.addWidget(self.clientPortEditToolButton, 1, 2, 1, 1)
        self.clientAddressEditToolButton = QtGui.QToolButton(self.clientTab)
        self.clientAddressEditToolButton.setIcon(icon)
        self.clientAddressEditToolButton.setCheckable(True)
        self.clientAddressEditToolButton.setObjectName(_fromUtf8("clientAddressEditToolButton"))
        self.gridLayout_2.addWidget(self.clientAddressEditToolButton, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.connectClientToolButton = QtGui.QToolButton(self.clientTab)
        self.connectClientToolButton.setEnabled(True)
        self.connectClientToolButton.setIcon(icon1)
        self.connectClientToolButton.setIconSize(QtCore.QSize(32, 32))
        self.connectClientToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.connectClientToolButton.setObjectName(_fromUtf8("connectClientToolButton"))
        self.horizontalLayout_2.addWidget(self.connectClientToolButton)
        self.disconnectClientToolButton = QtGui.QToolButton(self.clientTab)
        self.disconnectClientToolButton.setIcon(icon2)
        self.disconnectClientToolButton.setIconSize(QtCore.QSize(32, 32))
        self.disconnectClientToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.disconnectClientToolButton.setObjectName(_fromUtf8("disconnectClientToolButton"))
        self.horizontalLayout_2.addWidget(self.disconnectClientToolButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.tabWidget.addTab(self.clientTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        RemoteControlDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(RemoteControlDockWidget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.portEditToolButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.portSpinBox.setEnabled)
        QtCore.QObject.connect(self.serverAddressEditToolButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.serverAddressLineEdit.setEnabled)
        QtCore.QObject.connect(self.clientPortEditToolButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.clientPortSpinBox.setEnabled)
        QtCore.QObject.connect(self.clientAddressEditToolButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.clientAddressLineEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(RemoteControlDockWidget)

    def retranslateUi(self, RemoteControlDockWidget):
        RemoteControlDockWidget.setWindowTitle(QtGui.QApplication.translate("RemoteControlDockWidget", "Remote Control", None, QtGui.QApplication.UnicodeUTF8))
        self.serverAddressLineEdit.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.portLabel.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.serverAddressLabel.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.portEditToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.serverAddressEditToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.startServerToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "start Server", None, QtGui.QApplication.UnicodeUTF8))
        self.startServerToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "start Server", None, QtGui.QApplication.UnicodeUTF8))
        self.stopServerToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "shutdown Server", None, QtGui.QApplication.UnicodeUTF8))
        self.stopServerToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "shutdown Server", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.serverTab), QtGui.QApplication.translate("RemoteControlDockWidget", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.clientAddressLineEdit.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.clientPortLabel.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.clientAddressLabel.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.clientPortEditToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.clientAddressEditToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.connectClientToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "connect Client", None, QtGui.QApplication.UnicodeUTF8))
        self.connectClientToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "connect Client", None, QtGui.QApplication.UnicodeUTF8))
        self.disconnectClientToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "disconnect Client", None, QtGui.QApplication.UnicodeUTF8))
        self.disconnectClientToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "disconnect Client", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.clientTab), QtGui.QApplication.translate("RemoteControlDockWidget", "Client", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
