# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_remotecontroldockwidget.ui'
#
# Created: Mon Mar 10 11:29:15 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RemoteControlDockWidget(object):
    def setupUi(self, RemoteControlDockWidget):
        RemoteControlDockWidget.setObjectName(_fromUtf8("RemoteControlDockWidget"))
        RemoteControlDockWidget.resize(261, 298)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.serverTab = QtGui.QWidget()
        self.serverTab.setObjectName(_fromUtf8("serverTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.serverTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startStopServerToolButton = QtGui.QToolButton(self.serverTab)
        self.startStopServerToolButton.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/server-toggle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startStopServerToolButton.setIcon(icon)
        self.startStopServerToolButton.setIconSize(QtCore.QSize(32, 32))
        self.startStopServerToolButton.setCheckable(True)
        self.startStopServerToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.startStopServerToolButton.setObjectName(_fromUtf8("startStopServerToolButton"))
        self.horizontalLayout.addWidget(self.startStopServerToolButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.serverAddressLineEdit = QtGui.QLineEdit(self.serverTab)
        self.serverAddressLineEdit.setEnabled(False)
        self.serverAddressLineEdit.setObjectName(_fromUtf8("serverAddressLineEdit"))
        self.gridLayout.addWidget(self.serverAddressLineEdit, 0, 1, 1, 1)
        self.serverAddressLabel = QtGui.QLabel(self.serverTab)
        self.serverAddressLabel.setObjectName(_fromUtf8("serverAddressLabel"))
        self.gridLayout.addWidget(self.serverAddressLabel, 0, 0, 1, 1)
        self.serverAddressListenLocalhostToolButton = QtGui.QToolButton(self.serverTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/user-desktop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.serverAddressListenLocalhostToolButton.setIcon(icon1)
        self.serverAddressListenLocalhostToolButton.setCheckable(False)
        self.serverAddressListenLocalhostToolButton.setObjectName(_fromUtf8("serverAddressListenLocalhostToolButton"))
        self.gridLayout.addWidget(self.serverAddressListenLocalhostToolButton, 0, 3, 1, 1)
        self.serverPortEditToolButton = QtGui.QToolButton(self.serverTab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/draw-freehand.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.serverPortEditToolButton.setIcon(icon2)
        self.serverPortEditToolButton.setCheckable(True)
        self.serverPortEditToolButton.setObjectName(_fromUtf8("serverPortEditToolButton"))
        self.gridLayout.addWidget(self.serverPortEditToolButton, 1, 2, 1, 1)
        self.serverPortSpinBox = QtGui.QSpinBox(self.serverTab)
        self.serverPortSpinBox.setEnabled(False)
        self.serverPortSpinBox.setMinimum(1)
        self.serverPortSpinBox.setMaximum(65535)
        self.serverPortSpinBox.setProperty("value", 9615)
        self.serverPortSpinBox.setObjectName(_fromUtf8("serverPortSpinBox"))
        self.gridLayout.addWidget(self.serverPortSpinBox, 1, 1, 1, 1)
        self.serverPortLabel = QtGui.QLabel(self.serverTab)
        self.serverPortLabel.setObjectName(_fromUtf8("serverPortLabel"))
        self.gridLayout.addWidget(self.serverPortLabel, 1, 0, 1, 1)
        self.serverAddressEditToolButton = QtGui.QToolButton(self.serverTab)
        self.serverAddressEditToolButton.setIcon(icon2)
        self.serverAddressEditToolButton.setCheckable(True)
        self.serverAddressEditToolButton.setObjectName(_fromUtf8("serverAddressEditToolButton"))
        self.gridLayout.addWidget(self.serverAddressEditToolButton, 0, 2, 1, 1)
        self.serverAddressListenAllToolButton = QtGui.QToolButton(self.serverTab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/network-workgroup.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.serverAddressListenAllToolButton.setIcon(icon3)
        self.serverAddressListenAllToolButton.setCheckable(False)
        self.serverAddressListenAllToolButton.setObjectName(_fromUtf8("serverAddressListenAllToolButton"))
        self.gridLayout.addWidget(self.serverAddressListenAllToolButton, 0, 4, 1, 1)
        self.serverPortDefaultToolButton = QtGui.QToolButton(self.serverTab)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/draw-eraser.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.serverPortDefaultToolButton.setIcon(icon4)
        self.serverPortDefaultToolButton.setCheckable(False)
        self.serverPortDefaultToolButton.setObjectName(_fromUtf8("serverPortDefaultToolButton"))
        self.gridLayout.addWidget(self.serverPortDefaultToolButton, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.clientListView = QtGui.QListView(self.serverTab)
        self.clientListView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.clientListView.setAlternatingRowColors(True)
        self.clientListView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.clientListView.setObjectName(_fromUtf8("clientListView"))
        self.verticalLayout_2.addWidget(self.clientListView)
        self.tabWidget.addTab(self.serverTab, _fromUtf8(""))
        self.clientTab = QtGui.QWidget()
        self.clientTab.setObjectName(_fromUtf8("clientTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.clientTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.connectDisconnectClientToolButton = QtGui.QToolButton(self.clientTab)
        self.connectDisconnectClientToolButton.setEnabled(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/client-toggle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectDisconnectClientToolButton.setIcon(icon5)
        self.connectDisconnectClientToolButton.setIconSize(QtCore.QSize(32, 32))
        self.connectDisconnectClientToolButton.setCheckable(True)
        self.connectDisconnectClientToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.connectDisconnectClientToolButton.setObjectName(_fromUtf8("connectDisconnectClientToolButton"))
        self.horizontalLayout_2.addWidget(self.connectDisconnectClientToolButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.clientPortLabel = QtGui.QLabel(self.clientTab)
        self.clientPortLabel.setObjectName(_fromUtf8("clientPortLabel"))
        self.gridLayout_2.addWidget(self.clientPortLabel, 1, 0, 1, 1)
        self.taskbarHeightLabel = QtGui.QLabel(self.clientTab)
        self.taskbarHeightLabel.setObjectName(_fromUtf8("taskbarHeightLabel"))
        self.gridLayout_2.addWidget(self.taskbarHeightLabel, 2, 0, 1, 1)
        self.clientAddressLabel = QtGui.QLabel(self.clientTab)
        self.clientAddressLabel.setObjectName(_fromUtf8("clientAddressLabel"))
        self.gridLayout_2.addWidget(self.clientAddressLabel, 0, 0, 1, 1)
        self.windowbarHeightLabel = QtGui.QLabel(self.clientTab)
        self.windowbarHeightLabel.setObjectName(_fromUtf8("windowbarHeightLabel"))
        self.gridLayout_2.addWidget(self.windowbarHeightLabel, 3, 0, 1, 1)
        self.windowbarHeightSpinBox = QtGui.QSpinBox(self.clientTab)
        self.windowbarHeightSpinBox.setEnabled(True)
        self.windowbarHeightSpinBox.setMinimum(1)
        self.windowbarHeightSpinBox.setMaximum(65535)
        self.windowbarHeightSpinBox.setProperty("value", 26)
        self.windowbarHeightSpinBox.setObjectName(_fromUtf8("windowbarHeightSpinBox"))
        self.gridLayout_2.addWidget(self.windowbarHeightSpinBox, 3, 1, 1, 1)
        self.taskbarHeightSpinBox = QtGui.QSpinBox(self.clientTab)
        self.taskbarHeightSpinBox.setEnabled(True)
        self.taskbarHeightSpinBox.setMinimum(1)
        self.taskbarHeightSpinBox.setMaximum(65535)
        self.taskbarHeightSpinBox.setProperty("value", 79)
        self.taskbarHeightSpinBox.setObjectName(_fromUtf8("taskbarHeightSpinBox"))
        self.gridLayout_2.addWidget(self.taskbarHeightSpinBox, 2, 1, 1, 1)
        self.clientPortSpinBox = QtGui.QSpinBox(self.clientTab)
        self.clientPortSpinBox.setEnabled(False)
        self.clientPortSpinBox.setMinimum(1)
        self.clientPortSpinBox.setMaximum(65535)
        self.clientPortSpinBox.setProperty("value", 9615)
        self.clientPortSpinBox.setObjectName(_fromUtf8("clientPortSpinBox"))
        self.gridLayout_2.addWidget(self.clientPortSpinBox, 1, 1, 1, 1)
        self.clientAddressLineEdit = QtGui.QLineEdit(self.clientTab)
        self.clientAddressLineEdit.setEnabled(False)
        self.clientAddressLineEdit.setObjectName(_fromUtf8("clientAddressLineEdit"))
        self.gridLayout_2.addWidget(self.clientAddressLineEdit, 0, 1, 1, 1)
        self.clientAddressEditToolButton = QtGui.QToolButton(self.clientTab)
        self.clientAddressEditToolButton.setIcon(icon2)
        self.clientAddressEditToolButton.setCheckable(True)
        self.clientAddressEditToolButton.setObjectName(_fromUtf8("clientAddressEditToolButton"))
        self.gridLayout_2.addWidget(self.clientAddressEditToolButton, 0, 2, 1, 1)
        self.clientPortEditToolButton = QtGui.QToolButton(self.clientTab)
        self.clientPortEditToolButton.setIcon(icon2)
        self.clientPortEditToolButton.setCheckable(True)
        self.clientPortEditToolButton.setObjectName(_fromUtf8("clientPortEditToolButton"))
        self.gridLayout_2.addWidget(self.clientPortEditToolButton, 1, 2, 1, 1)
        self.clientPortDefaultToolButton = QtGui.QToolButton(self.clientTab)
        self.clientPortDefaultToolButton.setIcon(icon4)
        self.clientPortDefaultToolButton.setCheckable(False)
        self.clientPortDefaultToolButton.setObjectName(_fromUtf8("clientPortDefaultToolButton"))
        self.gridLayout_2.addWidget(self.clientPortDefaultToolButton, 1, 3, 1, 1)
        self.clientAddressListenLocalhostToolButton = QtGui.QToolButton(self.clientTab)
        self.clientAddressListenLocalhostToolButton.setIcon(icon1)
        self.clientAddressListenLocalhostToolButton.setCheckable(False)
        self.clientAddressListenLocalhostToolButton.setObjectName(_fromUtf8("clientAddressListenLocalhostToolButton"))
        self.gridLayout_2.addWidget(self.clientAddressListenLocalhostToolButton, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.tabWidget.addTab(self.clientTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        RemoteControlDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(RemoteControlDockWidget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.serverPortEditToolButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.serverPortSpinBox.setEnabled)
        QtCore.QObject.connect(self.serverAddressEditToolButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.serverAddressLineEdit.setEnabled)
        QtCore.QObject.connect(self.clientPortEditToolButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.clientPortSpinBox.setEnabled)
        QtCore.QObject.connect(self.clientAddressEditToolButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.clientAddressLineEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(RemoteControlDockWidget)

    def retranslateUi(self, RemoteControlDockWidget):
        RemoteControlDockWidget.setWindowTitle(QtGui.QApplication.translate("RemoteControlDockWidget", "Remote Control", None, QtGui.QApplication.UnicodeUTF8))
        self.startStopServerToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "start/stop server", None, QtGui.QApplication.UnicodeUTF8))
        self.startStopServerToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "start Server", None, QtGui.QApplication.UnicodeUTF8))
        self.serverAddressLineEdit.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.serverAddressLabel.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.serverAddressListenLocalhostToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "listen localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.serverAddressListenLocalhostToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.serverPortEditToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "edit port", None, QtGui.QApplication.UnicodeUTF8))
        self.serverPortEditToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.serverPortLabel.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.serverAddressEditToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "edit address", None, QtGui.QApplication.UnicodeUTF8))
        self.serverAddressEditToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.serverAddressListenAllToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "listen globaly", None, QtGui.QApplication.UnicodeUTF8))
        self.serverAddressListenAllToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.serverPortDefaultToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "set Port back to 9615", None, QtGui.QApplication.UnicodeUTF8))
        self.serverPortDefaultToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.serverTab), QtGui.QApplication.translate("RemoteControlDockWidget", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.connectDisconnectClientToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "connect/disconnect client", None, QtGui.QApplication.UnicodeUTF8))
        self.connectDisconnectClientToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "connect Client", None, QtGui.QApplication.UnicodeUTF8))
        self.clientPortLabel.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.taskbarHeightLabel.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "Taskbar\n"
"Height", None, QtGui.QApplication.UnicodeUTF8))
        self.clientAddressLabel.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.windowbarHeightLabel.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "Windowhead\n"
"Height", None, QtGui.QApplication.UnicodeUTF8))
        self.clientAddressLineEdit.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.clientAddressEditToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "edit address", None, QtGui.QApplication.UnicodeUTF8))
        self.clientAddressEditToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.clientPortEditToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "edit port", None, QtGui.QApplication.UnicodeUTF8))
        self.clientPortEditToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.clientPortDefaultToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "set Port back to 9615", None, QtGui.QApplication.UnicodeUTF8))
        self.clientPortDefaultToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.clientAddressListenLocalhostToolButton.setToolTip(QtGui.QApplication.translate("RemoteControlDockWidget", "set address to localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.clientAddressListenLocalhostToolButton.setText(QtGui.QApplication.translate("RemoteControlDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.clientTab), QtGui.QApplication.translate("RemoteControlDockWidget", "Client", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
